apiVersion: apps/v1
kind: Deployment
metadata:
  name: jen-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: jenkins
    spec:
      containers:
        - name: jen-container
          image: te97ja/dockermulti:latest
          volumeMounts:
          - name: satya-file 
            mountPath: /usr/local/tomcat/webapps/
      volumes:
        - name: satya-file
          secret:
            secretName: secret-name
