apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: default
spec:
  limits:
  - default:
      cpu: 1
      memory: 500mi
    defaultRequest:
      cpu: 0.4
      memory: 300mi
    type: Container

