apiVersion: apps/v1
kind: Deployment
metadata:
  name: jen-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: jenkins
    spec:
      containers:
        - name: jen-container
          image: te97ja/dockermulti:latest
          volumeMounts:
          - name: satya-ebs 
            mountPath: /usr/local/tomcat/webapps/
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 300Mi
      volumes:
        - name: satya-ebs
          persistentVolumeClaim:
            claimName: tomcat-claim
