apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: web
  ports:
    - name: nginx
      protocol: TCP
      port: 8090
      targetPort: 80
    - name: jenkins
      protocol: TCP
      port: 8060
      targetPort: 8080
