apiVersion: v1
kind: Service
metadata:
  name: nginxlb1
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 9090
      nodePort: 30335
      targetPort: 80
