---
apiVersion: v1
kind: Pod
metadata:
  name: multicontainerpod2
  labels:
    app: jenkinsnginx
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
