apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
spec:
  type: NodePort
  selector:
    app: jenkinsnginx
  ports:
    - name: nginx
      protocol: TCP
      port: 8090
      nodePort: 30333
      targetPort: 80
    - name: jenkins
      protocol: TCP
      port: 8060
      nodePort: 30444
      targetPort: 8080
