apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  clusterIP: 10.100.27.21
  selector:
    app: web
  ports:
    - name: nginx
      protocol: TCP
      port: 8090
      targetPort: 80
    - name: jenkins
      protocol: TCP
      port: 8060
      targetPort: 8080
  externalIPs:
    - 54.184.23.185
