apiVersion: v1
kind: Service
metadata:
  name: nginxlb
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 8889
      nodePort: 30547
      targetPort: 80
