apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-root-volume
  labels:
    type: aws-ebs-volume
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:                                                                                                                            
    volumeID: vol-0e9af4b2d9dce4de4
    fsType: ext4
